NYPL/design-toolkit

buttons.html, css/docs.css, css/example-styles.css, sass/_buttons.scss, sass/example-styles.scss
=> Button improvments

css/example-styles.css, sass/_colors.scss
#22  Fixed this issue. However in the page headers where we have a gray background we're still failing there. will create issue and fix...
=> fixed color contrast issue

css/docs.css, css/example-search-styles.css, css/example-styles.css, example.html, sass/_header.scss
- Added a hamburger menu to the mobile drop down. for comparison against the current down arrow treatment.
- Increased the size of the "button" to make it easier to press / tap
- Made some small adjustments so the logo feels more intentionally placed viz. the edge of the other neighboring elemenents.
=> mobile menu update

.scss-lint.yml, css/docs.css, css/example-search-styles.css, css/example-styles.css, discovery-search.html, example.html, js/header.js, sass/_forms.scss, sass/_header.scss
based on @ricardoom suggestions added space to the main search and removed id references in sass / rem-ified a bunch / fixes #125
there's a 1px vertical offset between the search button and text field which drives me a bit nuts but can be left alone for now (if someone knows how to align that, you're welcome to try it)
see screenshots:
=> added moar space to the main search

docs/_sections/design-resources.md
Section on design resources from accessibility repo.
=> Section on design resources :rocket:

docs/_sections/glossary.md
hello. In migrating stuff from that accessibility repo, I've created a glossary.
=> I made a glossary

docs/_sections/forms.html
updated usage documentation, and added additional aria attributes to the fields.
also fixes #51
=> add error states

docs/Gemfile.lock, docs/_sections/color.md, docs/_sections/forms.html, docs/css/docs.css, docs/css/example-search-styles.css, docs/css/example-styles.css, sass/_colors.scss, sass/_toolkit.scss, sass/docs.scss
simple swatch / defs for existing color set
=> add color swatches

docs/_sections/color.md, docs/css/docs.css, sass/_colors.scss, sass/docs.scss
=> reeeeeesaturateeeed

docs/_sections/buttons.html
=> renamed our primary button, "Primary Action Button"

docs/_sections/forms.html, docs/css/docs.css, docs/css/example-search-styles.css, docs/css/example-styles.css, docs/js/header.js, sass/_buttons.scss, sass/_general-mixins.scss, sass/_toolkit.scss
also made the style a general mixin (no longer only button-specific)
=> :space_invader: added mixin and examples for a spinner field

docs/css/docs.css, docs/css/example-search-styles.css, docs/css/example-styles.css, sass/_toolkit.scss, sass/example-search-styles.scss, sass/example-styles.scss
:space_invader: moved the `.hidden` class to toolkit.scss
=> :space_invader: now with less .hidden

docs/js/header.js
=> :space_invader: blurring ftw

docs/_sections/forms.html
=> :space_invader: better doc of spinner

docs/_sections/forms.html
=> :space_invader: doc fix for spinner

docs/_sections/buttons.html, docs/css/docs.css, docs/css/example-search-styles.css, docs/css/example-styles.css, sass/_buttons.scss, sass/_toolkit.scss
for the button formerly known as request, plus updated docs in `basic-button`
=> :space_invader: updated mixin (with legacy support)

README.md, package.json
amended README and `package.json` to reflect the new version
=> version bumpin' to 0.1.11

docs/_sections/forms.html, docs/css/example-search-styles.css, docs/css/example-styles.css, docs/js/header.js, sass/_general-mixins.scss
because everyone should be allowed to spin 🌀
=> :space_invader: added omnisearch to spinner examples

docs/_sections/tables.html, docs/css/example-search-styles.css, docs/css/example-styles.css, docs/discovery-search.html, sass/_tables-results.scss
=> :space_invader: better remove facet widget

docs/css/example-search-styles.css, docs/css/example-styles.css, docs/discovery-home.html, sass/_microformats.scss
removed lower content. added top text. see https://github.com/NYPL-discovery/discovery-front-end/issues/212
=> :space_invader: fixes NYPL-discovery/discovery-front-end#212

docs/_sections/tables.html, docs/css/example-search-styles.css, docs/css/example-styles.css, docs/discovery-search.html, sass/_tables-results.scss, sass/_toolkit.scss
to address this issue: https://github.com/NYPL-discovery/discovery-front-end/issues/240
=> Improved results

docs/_sections/forms.html, docs/css/example-search-styles.css, docs/css/example-styles.css, docs/js/header.js, sass/_forms.scss
=> :space_invader: updated date field to html5

docs/_sections/forms.html, docs/js/header.js
=> :space_invader: better required field

docs/_sections/forms.html, docs/discovery-search.html, docs/js/header.js
=> :space_invader: fixes issue-97

docs/_sections/about.md, docs/css/docs.css, docs/css/example-search-styles.css, docs/css/example-styles.css, sass/_nypl-normalize.scss, sass/_typography.scss, sass/docs.scss
you can better see/read the text in this link: https://github.com/NYPL/design-toolkit/blob/about/docs/_sections/about.md
=> :space_invader: first pass at an about page

.scss-lint.yml, docs/css/example-search-styles.css, docs/css/example-styles.css, docs/discovery-home.html, docs/discovery-item.html, docs/discovery-search.html, sass/_grid.scss, sass/_nypl-normalize.scss, sass/_tables-results.scss
=> addressing header titles

docs/_sections/tables.html
for the item search results. issue: #111
=> :space_invader: added docs

docs/_sections/tables.html, docs/css/example-search-styles.css, docs/css/example-styles.css, docs/discovery-search.html, docs/svg/times.icon.svg, sass/_icons.scss, sass/_tables-results.scss
related to: https://github.com/NYPL-discovery/discovery-front-end/pull/278#issuecomment-300972946
fixes #116
=> :space_invader: remove facet as svg

docs/css/example-search-styles.css, docs/css/example-styles.css, sass/_tables-results.scss
a little border in the item that ties the room together
=> :space_invader: added a border to item info

docs/css/example-search-styles.css, docs/css/example-styles.css, sass/_general-mixins.scss, sass/_nypl-normalize.scss
more breathing room in some areas
=> Moar space

docs/_sections/tables.html, docs/css/example-search-styles.css, docs/css/example-styles.css, docs/discovery-search.html, sass/_tables-results.scss
better structuring of search results item (see #139)
=> :space_invader: first pass at fixing #139

docs/_sections/tables.html, docs/css/example-search-styles.css, docs/css/example-styles.css, docs/discovery-search.html, docs/js/header.js, sass/_tables-results.scss
addresses https://github.com/NYPL-discovery/discovery-front-end/issues/317
=> :space_invader: fixes #128

docs/discovery-item.html
=> :space_invader: fixes #130

docs/_sections/tables.html, docs/css/example-search-styles.css, docs/css/example-styles.css, docs/discovery-search.html, sass/_tables-results.scss
fixes the facet big box problem
=> :space_invader: better remove facet / fixes #122 fixes #125

docs/_layouts/default.html, docs/css/example-search-styles.css, docs/css/example-styles.css, docs/discovery-item.html, docs/discovery-search.html, sass/_general-mixins.scss, sass/_tables-results.scss
now item with alternate titles
=> Item title

docs/_sections/forms.html, docs/css/example-search-styles.css, docs/css/example-styles.css, docs/discovery-search.html, sass/_forms.scss, sass/_toolkit.scss
=> :space_invader: using input type number in date search

docs/_sections/tables.html, docs/css/example-search-styles.css, docs/css/example-styles.css, docs/discovery-search.html, sass/_tables-results.scss
=> :space_invader: a11y fixes - fixes #135 fixes #134

docs/css/example-search-styles.css, docs/css/example-styles.css, sass/_general-mixins.scss
=> :space_invader: collapsed facet no longer read by screen readers

docs/_sections/forms.html, docs/css/example-search-styles.css, docs/css/example-styles.css, docs/discovery-home.html, docs/discovery-item.html, docs/discovery-search.html, sass/_forms.scss
new order for omnibox fields / fixes #150
=> new order for omnibox fields / fixes #150

docs/_layouts/default.html, docs/_layouts/home.html, docs/_sections/layout.html, docs/discovery-holds.html, docs/discovery-home.html, docs/discovery-item.html, docs/discovery-search.html, docs/example.html, docs/example_card.html, docs/example_events.html
added aria, roles, and “you are here in breadcrumbs” per #153
=> better a11y in breadcrumbs

INSTALL.md, design-toolkit.gemspec, lib/design-toolkit.rb, lib/design-toolkit/engine.rb, lib/design-toolkit/version.rb
because why not
this should not interfere with npm in any way
=> toolkit Ruby gem

docs/_resources/resources.md
TODO: generate policy and workflows for devs, design and content creators
=> :meat_on_bone: added two more resources for a11y validations

docs/_sections/tables.html
=> :meat_on_bone: fixes #165 

docs/Gemfile.lock, docs/_resources/development-checklist.md, docs/_resources/resources.md
Bones for a first draft checklist of concrete WCAG 2.0 conformance guidelines. List is intended to help _set foundation_ for accessibility and start conversation. 
#167 contains related open issues.
=> Checklist draft

docs/css/example-search-styles.v2.css, docs/discovery-item.v2.html, sass/example-search-styles.v2.scss
please run and confirm its not all kinds of busted up. 
For comparison:
[https://drive.google.com/file/d/0B2LQIUUuUDJdcl9XSm56WDhFV0k/view?usp=sharing](https://drive.google.com/file/d/0B2LQIUUuUDJdcl9XSm56WDhFV0k/view?usp=sharing)
=> Hotfix field update

docs/discovery-item.v2.html, docs/discovery-search.v3.html
Fixes #184. Add examples for an item that would be requestable but is already in use.
=> Add in-use example

docs/discovery-item.html, docs/discovery-search.html
Add back in-use message examples
=> In use message 2

docs/request-confirmation.html
fixes:
https://github.com/NYPL-discovery/discovery-front-end/issues/676
=> Fix for discovery #676

docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, docs/discovery-home.html, docs/discovery-item.html, docs/discovery-search.html, sass/_forms.scss, sass/_omni-search.scss
So I've used @EdwinGuzman's markup 
Please dig.
=> Fix #195 for reals

docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, docs/discovery-item.html, docs/discovery-search.html, docs/edd-request-form.html, sass/_grid.scss, sass/_tables-results.scss
this should cover all the updates for the Headers (Titling spaces w/ breadcrumbs at the top of each page)
https://github.com/NYPL-discovery/discovery-front-end/issues/679
https://github.com/NYPL-discovery/discovery-front-end/issues/674
After this one is done, I can proceed to merge to master and `npm` publish
=> Update Page Headers

docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, docs/edd-request-form.html, sass/_forms.scss, sass/_general-mixins.scss, sass/_toolkit.scss
does some work on the form for EDD. removes the border around the whole thing and addresses some a11y issues which need reviewing form completeness and correctness...
=> Improve request screens

docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, docs/discovery-search.html, sass/_grid.scss, sass/_tables-results.scss
a more proper way of doing it... see the last two commits...
=> better spacing

docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, docs/discovery-search.html, sass/_forms.scss, sass/_grid.scss, sass/_tables-results.scss, sass/_toolkit.scss
fixes the select drop down on search results. 
issue:
https://jira.nypl.org/browse/DIS-119
=> Fix select sorting

docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, docs/edd-request-form.html, sass/_forms.scss
=> Fixes #210

docs/_sections/forms.html, docs/_sections/tables.html, docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, docs/discovery-home.html, docs/discovery-item.html, docs/discovery-request.html, docs/discovery-search.html, docs/edd-request-form.html, docs/example_events.html, sass/_buttons.scss, sass/_forms.scss, sass/_header.scss, sass/_microformats.scss, sass/_omni-search.scss, sass/_tables-results.scss, sass/example-search-styles.v2.scss
Fixes the all capitalization issue(s) outlined in #192
=> Fix casing #192

README.md, docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, sass/_tables-results.scss
Now all table items in search results are scrolling on small screens and all the contents of the table are visible, no more hiding stuff... Fixes #158
=> Update inline results tables

docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, sass/_tables-results.scss
fixes a the overall table width shrinking on large screens.
=> fixes shrinking tables

docs/_sections/microformats.html
:meat_on_bone: quick copy update for incomplete documentation
=> documentation update

docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, docs/discovery-search.html, sass/_css3.scss, sass/_general-mixins.scss, sass/_modal.scss, sass/_toolkit.scss
very basic columns set up for the filters
=> :meat_on_bone: added columns in css for filters

docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, sass/_forms.scss
- add vendor prefixes to the checkbox transform
=> #233 Hotfix

docs/Gemfile.lock, docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, docs/discovery-search.html, sass/_modal-container.scss, sass/_modal.scss
For #232 
Turn JS off.
Try this out. It's only for the search results page: http://local.nypl.org:4000/design-toolkit/discovery-search.html
=> Adding js/css for the no-js popup solution.

docs/_sections/icons/check.circle.rev.icon.svg, docs/_sections/icons/close.circle.icon.svg, docs/_sections/svg-index.html, docs/_sections/tables.html, docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, docs/js/header.js, sass/_buttons.scss, sass/_tables-results.scss
as a result of updating the svg icons, more things needed fixing and cleaning up
fixes #246
=> Fix more SVG issues

docs/_config.yml, docs/_includes/blog-nav.html, docs/_includes/left-nav.html, docs/_resources/nypl-index.md, docs/css/docs.css, sass/docs.scss
=> Add project index

.travis.yml, docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, sass/_buttons.scss, sass/_tables-results.scss
setting `whitespace: normal` for buttons.
=> Adjust button box

docs/_sections/forms.html, docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, sass/_colors.scss, sass/_forms.scss, sass/_toolkit.scss
added a success state for form submissions
=> fixes #252

docs/_sections/forms.html, docs/css/docs.css, docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, docs/edd-request-form.html, sass/_colors.scss, sass/_forms.scss, sass/_toolkit.scss
added basic `<textarea>` markup and styles (default, success, & error states)
@wlla if you could let me know if there are a11y issues I would appreciate.
=> Add text area #254

docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, docs/discovery-item.html, docs/discovery-request.html, docs/discovery-search.html, docs/edd-request-form.html, docs/request-confirmation.html, sass/_grid.scss, sass/_measurements.scss
fixes #256 yeah.
@EdwinGuzman is the only one who _has_ to review... but I added you other two in case you were interested...
=> Better page content alignment #256

docs/_sections/color.md, docs/_sections/forms.html, docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, sass/_forms.scss
=> Minor fixes

docs/_sections/tables.html, docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, docs/discovery-search.html, sass/_forms.scss, sass/_media-queries.scss, sass/_tables-results.scss, sass/_toolkit.scss, sass/example-search-styles.v2.scss
fixes #265 & #266
@rhernand3z / @ktp242 you're just added on for completion. feel free to review and let me know if you see anything wildly out of order.
=> Update dropdowns #265

INSTALL.md
=> Adding documentation for installing using webpack 2.x.x

docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, docs/discovery-item.html, docs/discovery-request.html, docs/discovery-search.html, docs/edd-request-form.html, docs/request-confirmation.html, sass/_tables-results.scss, sass/_toolkit.scss
=> Update from discovery

docs/_sections/forms.html, docs/css/example-search-styles.css, docs/css/example-search-styles.v2.css, docs/css/example-styles.css, sass/_forms.scss
updated select controls for use in other applications...
=> Minor form update

README.md, gulpfile.js
updated the gulp commands and some documentation on how to use
=> updated docs to cover use of gulp

.npmignore, CHANGELOG.md, package-lock.json, package.json
=> Changes for node 10.
